# Generated by Django 3.1.2 on 2021-01-26 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='https://d3e54v103j8qbb.cloudfront.net/img/background-image.svg', upload_to='static/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 15, 29, 43, 854225, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
