# Generated by Django 3.1.2 on 2021-01-27 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210127_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=models.CharField(default='#5cc489', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 18, 35, 3, 884268, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
