# Generated by Django 3.1.2 on 2021-01-28 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210127_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='details about this post', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 3, 16, 10, 437334, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
