# Generated by Django 3.1.2 on 2021-02-06 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210206_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 1, 24, 45, 563733, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
