# Generated by Django 3.1.2 on 2021-02-08 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210206_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 17, 33, 29, 815146, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
