# Generated by Django 3.1.2 on 2021-02-09 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210208_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(default='no content yet', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 16, 43, 50, 631068, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
