# Generated by Django 3.1.2 on 2021-02-06 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210206_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 1, 24, 45, 565818, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
