# Generated by Django 3.1.2 on 2021-02-06 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210206_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='details about this project', max_length=1000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 1, 49, 39, 12492, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
