# Generated by Django 3.1.2 on 2021-02-06 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210206_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 2, 28, 45, 942955, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
