# Generated by Django 3.1.2 on 2021-02-08 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210208_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 18, 22, 2, 94126, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
