# Generated by Django 3.1.2 on 2021-02-05 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 17, 35, 36, 747589, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
