# Generated by Django 3.1.2 on 2021-02-11 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tutorials', '0024_auto_20210211_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 19, 18, 58, 790125, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
